const languages_frameworks = [
    "Astro",
    "Python",
    "JavaScript",
    "Java",
    "C++",
    "Ruby",
    "Swift",
    "PHP",
    "Go",
    "Rust",
    "Kotlin",
    "C#",
    "PHP",
    "TypeScript",
    "HTML/CSS",
    "Node.js",
    "React",
    "Angular",
    "Vue.js",
    "Django",
    "Ruby on Rails",
    "Spring Boot",
    "Express.js",
    "Laravel",
    "ASP.NET",
    "Flutter",
    "TensorFlow",
    "PyTorch",
    "Bootstrap",
    "jQuery",
    "Symfony",
    "Flask",
    "ASP.NET Core",
    "Vue.js",
    "Ember.js",
    "Ruby on Rails",
    "XML",
    "Dart"
]

export default languages_frameworks